image: cypress/base:12.16.1

# CACHE #

cache:
  key: the-one-and-only-cache-key
  paths:
    - .npm
    - cache/Cypress
    - node_modules

before_script:
  - npm ci --cache .npm --prefer-offline
  - npx cypress cache path
  - npx cypress cache list


# JOBS #

stages:
  - test
  - deploy


test:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npx cypress cache path
    - npx cypress cache list
  script:
    - npm run cy:verify
    - npm run test

deploy:
  stage: deploy
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - echo ${CI_COMMIT_SHA:0:8}
    - npm run export
    - git clone git@github.com:LenaSchnedlitz/LenaSchnedlitz.github.io.git
    - mv __sapper__/export/* LenaSchnedlitz.github.io
    - git add .
    - git commit -m ${CI_COMMIT_SHA:0:8}
    - git push
  artifacts:
    paths:
      - public
  only:
    - master
