image: cypress/base:16.13.0

# VARIABLES AND CACHE #

variables:
  DEPLOY_USER: 'LenaSchnedlitz'
  DEPLOY_REPO_NAME: 'LenaSchnedlitz.github.io'

cache:
  key: the-one-and-only-cache-key
  paths:
    - .npm
    - node_modules

before_script:
  - npm ci --cache .npm --prefer-offline


# JOBS #

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run export
    # clone deploy repo and throw away all content but .git/ and CNAME
    - git clone https://github.com/${DEPLOY_USER}/${DEPLOY_REPO_NAME}.git
    - mv ${DEPLOY_REPO_NAME} ${DEPLOY_REPO_NAME}-old
    - mkdir ${DEPLOY_REPO_NAME}
    - mv -t ${DEPLOY_REPO_NAME} ${DEPLOY_REPO_NAME}-old/.git ${DEPLOY_REPO_NAME}-old/CNAME
    # add newly built content
    - cp -rf build/* ${DEPLOY_REPO_NAME}
    - cd ${DEPLOY_REPO_NAME}
    - git add .
    # commit and push
    - git config user.name "Lena Schnedlitz"
    - git config user.email ${GITLAB_USER_EMAIL}
    - git commit -m ${CI_COMMIT_SHORT_SHA}
    - git push https://LenaSchnedlitz:${DEPLOY_TOKEN}@github.com/${DEPLOY_USER}/${DEPLOY_REPO_NAME}.git HEAD
  only:
    - master
