image: cypress/base:12.16.1

# CACHE #

cache:
  key: the-one-and-only-cache-key
  paths:
    - .npm
    - cache/Cypress
    - node_modules

before_script:
  - npm ci
  - npx cypress cache path
  - npx cypress cache list
  - npm run cy:verify


# JOBS #

stages:
  - test
  - deploy


test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    - npm run test
    - npm run export
    - mv __sapper__/export public
    - git --version
  artifacts:
    paths:
      - public
  only:
    - master
