image: cypress/base:12.16.1

cache:
  key: the-one-and-only-cache-key
  paths:
    - .npm
    - cache/Cypress
    - node_modules

stages:
  - test
  - deploy


test:
  stage: test
  script:
    - npm run test
  except:
    - master

deploy:
  stage: deploy
  script:
    - npm run test
    - npm run export
    - mv __sapper__/export public
  artifacts:
    paths:
      - public
  only:
    - master